angka_1 = int(input("Masukkan Angka Pertama: "))
angka_2 = int(input("Masukkan Angka Kedua: "))
print(f"Penjumlahan: {angka_1 + angka_2}")
print(f"Pengurangan: {angka_1 - angka_2}")
print(f"Perkalian: {angka_1 * angka_2}")
print(f"Pembagian: {angka_1 / angka_2}")
